---
title: Aggregated inputs
author: Sara Altman
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(lubridate)
library(tidymodels)

# Parameters
  # Starting date
MIN_DATE <- "2008-01-01"
  # Ending date
MAX_DATE <- "2019-12-31"
  # Year to standardize values to
STANDARDIZE_YEAR <- 2012
  
vars_compute <- c("imagenet", "penn_treebank", "median_pfd")
var_output <- "sota_total_pct_change"

file_compute <-  
  here::here("data-raw/compute.csv")
file_funding <-
  here::here("data-raw/funding.csv")
file_sota <- 
  here::here("data/sota/sota.rds")
file_imagenet <- here::here("data-raw/imagenet.csv")
file_penn_treebank <-  
  here::here("data-raw/penn_treebank.csv")
file_authors <-       
  here::here("data/microsoft/ms_authors.rds")
#===============================================================================

# Geometric mean function
gm_mean = function(x, na.rm = TRUE){
  exp(sum(log(x[x > 0]), na.rm = na.rm) / length(x))
}

# Read in individual data sets
imagenet <- 
  read_csv(file_imagenet) %>% 
  transmute(year = as.integer(year), compute) %>% 
  rename(imagenet = compute)

penn_treebank <-
  read_csv(file_penn_treebank) %>% 
  select(year, compute = `compute (pfs)`) %>% 
  drop_na(compute) %>% 
  mutate(year = floor(year)) %>% 
  rename(penn_treebank = compute)

funding <- 
  read_csv(file_funding) %>% 
  drop_na(funding) %>% 
  select(year, funding)
  
compute <- 
  read_csv(file_compute) %>% 
  group_by(year = year(publication_date)) %>% 
  summarize(median_pfd = median(overall_peta_flop_days))

sota <- 
  read_rds(file_sota) %>% 
  mutate(year = year(paper_date)) %>% 
  filter(year <= year(MAX_DATE)) %>% 
  group_by(year) %>% 
  summarize(sota_total_pct_change = sum(percent_change) * 100) 

researchers <-
  file_authors %>% 
  read_rds() %>% 
  filter(date <= MAX_DATE) %>% 
  group_by(year = year(date)) %>% 
  summarize(total_authors = max(total_authors))

all <-
  list(researchers, funding, sota, compute, imagenet, penn_treebank) %>% 
  reduce(full_join, by = "year") %>% 
  filter(year >= year(MIN_DATE)) %>% 
  pivot_longer(
    cols = -year, 
    names_to = "variable", 
    values_to = "value",
    values_drop_na = TRUE
  ) %>% 
  group_by(variable) %>% 
  mutate(
    year = year - 1,
    value = value / first(value, order_by = year)
  ) %>% 
  ungroup() %>% 
  drop_na(value)

avg_compute <-
  all %>% 
  filter(variable %in% vars_compute) %>% 
  group_by(year, variable = "avg_compute") %>%
  summarize(value = gm_mean(value)) %>% 
  ungroup() %>% 
  mutate(value = value / value[year == 2012])

avg_input <-
  all %>% 
  filter(variable != var_output) %>% 
  group_by(year, variable = "avg_input") %>% 
  summarize(value = gm_mean(value)) %>% 
  ungroup() %>% 
  mutate(value = value / value[year == 2012])

df <-
  all %>% 
  filter(!variable %in% vars_compute) %>% 
  group_by(variable) %>% 
  mutate(value = value / value[year == 2012]) %>% 
  ungroup()
```

## Models

```{r}
# Output data
outputs <-
  df %>% 
  filter(variable == "sota_total_pct_change") 

# Input data
inputs <-
  avg_input %>% 
  mutate(log_value = log10(value))

# Model spec
lm_spec <-
  linear_reg() %>% 
  set_engine(engine = "lm")

output_fit <- 
  lm_spec %>% 
  fit(formula = value ~ year, data = outputs)

input_fit <- 
  lm_spec %>% 
  fit(
    formula = log_value ~ year, 
    data = inputs 
  )

inputs %>% 
  ggplot(aes(year, log_value)) +
  geom_point() +
  scale_y_log10()
```


```{r message=FALSE}
labels <-
  c(
    # "avg_compute" = "Average compute",  
    # "funding" = "Funding",  
    # "total_authors" = "Total authors",
    "avg_input" = "Average input",
    "sota_total_pct_change" = "Output:\nSum of SOTA\npercent change"
  )

v <-
  outputs %>% 
  bind_rows(avg_input)

model_preds <-
  tibble(
    variable = "sota_total_pct_change",
    year = seq(min(outputs$year), max(outputs$year), by = 0.25)
  ) %>% 
  modelr::add_predictions(output_fit$fit) %>% 
  bind_rows(
    tibble(
      variable = "avg_input",
      year = seq(min(avg_input$year), max(avg_input$year), by = 0.25)
    ) %>% 
      modelr::add_predictions(input_fit$fit) %>% 
      mutate(pred = 10 ^ pred)
  )

df %>% 
  filter(variable != "sota_total_pct_change") %>% 
  bind_rows(avg_compute) %>% 
  ggplot(aes(year, value)) +
  geom_hline(yintercept = 1, color = "white", size = 1) +
  geom_point(aes(shape = variable), color = "#92c5de") +
  geom_point(aes(color = variable), data = v) +
  geom_smooth(aes(color = variable)) +
  # geom_line(aes(y = pred, color = variable), data = model_preds) +
  scale_x_continuous(breaks = scales::breaks_width(1)) +
  scale_y_log10(breaks = scales::breaks_log(7)) +
  scale_color_manual(values = c("#0571b0", "#ca0020"),labels = labels) +
  scale_shape_discrete(labels = labels) +
  guides(color = guide_legend(order = 1)) +
  labs(
    x = "Year",
    y = "Factor increase from first data point (log scale)",
    color = NULL,
    shape = "Inputs",
    title = "Inputs to and outputs from AI research over time",
    subtitle = 
      "Inputs (blue) have risen exponentially while outputs (red) have only increased linearly"
  )

outputs %>% 
  bind_rows(inputs) %>% 
  ggplot(aes(year, value, color = variable)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  scale_x_continuous(breaks = scales::breaks_width(2)) +
  scale_y_log10() +
  scale_color_discrete(labels = labels) +
  labs(
    x = "Year",
    y = "Factor increase from first data point\n(log scale)",
    color = NULL,
    title = "Inputs to and outputs from AI research over time",
    subtitle = "Inputs increasing more quickly than outputs"
  )
```

## Model stats

```{r}
summary(input_fit$fit)
summary(output_fit$fit)
```



```{r}


output <- 
  v %>% 
  filter(variable == "output_percent_change")

v_ <-
  v %>% 
  filter(variable != "output_percent_change")

v_ %>% 
  ggplot(aes(year, value, color = label)) +
  geom_line(alpha = 0.5) +
  geom_point(aes(color = label), alpha = 0.5, size = 1) +
  geom_line(data = output, size = 0.5) +
  geom_point(data = output, size = 1.2) +
  scale_color_manual(
    breaks = labels$label, 
    values = labels$color
  ) +
  scale_x_continuous(breaks = seq(2010, 2019, 2)) +
  scale_y_log10(
    breaks = 10 ^ (-1:6),
    labels = 
      format(10 ^ (-1:6), big.mark = ",", scientific = FALSE) %>% 
      str_remove(pattern = "\\.0+")
  ) +
  guides(color = guide_legend(reverse = TRUE)) +
  labs(
    title = "All inputs and output over time",
    subtitle = "Output (in black) growing more slowly than many inputs",
    x = "Year", 
    y = "Factor increase (log scale)",
    color = NULL
  ) +
  theme(legend.text = element_text(size = 6))
```

## Option 2 

```{r}
v_ %>% 
  ggplot(aes(year, value, color = label)) +
  geom_line() +
  geom_point(aes(color = label)) +
  geom_line(data = output) +
  geom_point(data = output) +
  scale_color_manual(
    breaks = labels_$label, 
    values = labels_$color
  ) +
  scale_x_continuous(breaks = seq(2010, 2019, 2)) +
  scale_y_log10(
    breaks = 10 ^ (-2:6),
    labels = format(10 ^ (-2:6), big.mark = ",", scientific = FALSE)
  ) +
  guides(color = guide_legend(reverse = TRUE)) +
  labs(
    title = "All inputs and output over time",
    x = "Year", 
    y = "Factor increase (log scale)",
    color = NULL
  ) +
  theme(legend.text = element_text(size = 6))
```

## Option 3

```{r}
v <-
 all %>% 
  pivot_longer(
    cols = -year, 
    names_to = "variable", 
    values_to = "value",
    values_drop_na = TRUE
  ) %>% 
  group_by(variable) %>% 
  mutate(value = value / first(value, order_by = year)) %>% 
  ungroup() %>% 
  filter(year >= 2010) %>% 
  drop_na(value) 

output <- 
  v %>% 
  filter(variable == "output_percent_change") %>% 
  mutate(input_output = "Output")

v_ <-
  v %>% 
  filter(variable != "output_percent_change") %>% 
  mutate(input_output = "Input")

v_ %>% 
  ggplot(aes(year, value, color = input_output, group = variable)) +
  geom_line() +
  geom_line(data = output) +
  geom_point(data = output) +
  scale_color_manual(
    values = c("gray75", "#d73027")
  ) +
  scale_x_continuous(breaks = seq(2010, 2019, 2)) +
  scale_y_log10(
    breaks = 10 ^ (-1:6),
    labels = 
      format(10 ^ (-1:6), big.mark = ",", scientific = FALSE) %>% 
      str_remove(pattern = "\\.0+")
  ) +
  guides(color = guide_legend(reverse = TRUE)) +
  labs(
    title = "All inputs and output over time",
    subtitle = "Many inputs are growing faster than the output",
    x = "Year", 
    y = "Factor increase (log scale)",
    color = NULL
  ) +
  theme(legend.text = element_text(size = 6))
```


## Option 4

```{r}
v <-
 all %>% 
  pivot_longer(
    cols = -year, 
    names_to = "variable", 
    values_to = "value",
    values_drop_na = TRUE
  ) %>% 
  group_by(variable) %>% 
  mutate(value = value / first(value, order_by = year)) %>% 
  ungroup() %>% 
  filter(year >= 2010) %>% 
  drop_na(value) %>% 
  left_join(labels, by = "variable") %>% 
  mutate(
    group = 
      case_when(
        str_detect(label, "[Cc]ompute") ~ "Compute",
        str_detect(label, "Output")  ~ "Output",
        TRUE                         ~ "Other input"
      )
  )

output <- 
  v %>% 
  filter(variable == "output_percent_change") 

v_ <-
  v %>% 
  filter(variable != "output_percent_change") 

v_ %>% 
  ggplot(aes(year, value, group = variable, color = group)) +
  geom_point(alpha = 0.75) +
  geom_line(alpha = 0.75) +
  geom_line(data = output) +
  geom_point(data = output) +
  scale_color_manual(
    breaks = c("Compute", "Other input", "Output"),
    values = c(scales::hue_pal()(2), "black")
  ) +
  scale_x_continuous(breaks = seq(2010, 2019, 2)) +
  scale_y_log10(
    breaks = 10 ^ (-1:6),
    labels = 
      format(10 ^ (-1:6), big.mark = ",", scientific = FALSE) %>% 
      str_remove(pattern = "\\.0+")
  ) +
  guides(color = guide_legend(reverse = TRUE)) +
  labs(
    title = "All inputs and output over time",
    subtitle = "Compute inputs are growing more quickly than the output",
    x = "Year", 
    y = "Factor increase (log scale)",
    color = NULL
  ) +
  theme(legend.text = element_text(size = 6))
```


