---
title: Papers with Code - SOTA
author: Sara Altman 
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(lubridate)

# Parameters
MIN_OBSERVATIONS <- 5
file_sota <- here::here("data/sota/sota.rds")
file_group_counts <- here::here("data/sota/groups.rds")
#===============================================================================

groups <-
  file_group_counts %>% 
  read_rds() %>% 
  filter(n >= MIN_OBSERVATIONS)

sota <-
  file_sota %>% 
  read_rds() %>% 
  drop_na(paper_date, metric_result) %>% 
  group_by(group) %>% 
  mutate(
    n_results = n(),
    metric_result = if_else(minimize, metric_result * -1, metric_result),
    percent_change_lag = 
      (metric_result - lag(metric_result, order_by = paper_date)) / 
      abs(lag(metric_result, order_by = paper_date)),
    days_since_first_paper = (min(paper_date) %--% paper_date) / days(1)
  ) %>% 
  ungroup() 

# %>% 
  # filter(percent_change_lag > 0)

# %>% 
  # filter(group %in% groups$group)

# When were most of the first papers?
```

## Percent change over time

### Days since first paper

```{r message=FALSE, warning=FALSE}
sota %>%  
  ggplot(aes(days_since_first_paper, percent_change_lag)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm") +
  scale_y_log10(labels = scales::label_percent(accuracy = 1)) 
```

```{r}
sota %>%  
  unnest(categories) %>% 
  ggplot(aes(paper_date, percent_change_lag, color = categories)) +
  geom_smooth(method = "lm", se = FALSE) +
  scale_y_log10(labels = scales::label_percent(accuracy = 1)) 
```


### Date

```{r message=FALSE, warning=FALSE}
sota %>% 
  unnest(categories) %>% 
  filter(percent_change > 0) %>% 
  ggplot(aes(paper_date, percent_change_lag)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm") 
  scale_y_log10(labels = scales::label_percent(accuracy = 1)) 
```


```{r}
sota %>% 
  group_by(year = year(paper_date)) %>%
  summarize(
    n_10 = sum(percent_change_lag > 0.1, na.rm = TRUE),
    n_20 = sum(percent_change_lag > 0.2, na.rm = TRUE),
    n_30 = sum(percent_change_lag > 0.3, na.rm = TRUE),
    n_50 = sum(percent_change_lag > 0.5, na.rm = TRUE),
    n_100 = sum(percent_change_lag > 1, na.rm = TRUE),
    across(c(n_10, n_20, n_30, n_50, n_100), list(percent = ~ (. / n()) * 100))
  )
```

```{r}
sota %>%  
  filter(percent_change_lag >= .1) %>%
  count(year = year(paper_date)) %>%
  ggplot(aes(year, n)) +
  geom_point() +
  geom_line()

sota %>% 
  filter(percent_change_lag > 0) %>%
  count(year = year(paper_date), wt = percent_change_lag) %>%
  ggplot(aes(year, n)) +
  geom_point() +
  geom_line()

# counts of the papers 1 + 1 + 1
# for each year: 1 * percent_change + percent_per

```


### Categories

```{r}
sota %>% 
  unnest(categories) %>% 
  filter(percent_change > 0) %>% 
  ggplot(aes(days_since_first_paper, percent_change_lag, group = group)) +
  geom_line(alpha = 0.5) +
  facet_wrap(vars(categories)) +
  scale_y_log10() 
```

### Datasets

```{r fig.asp=1}
sota %>%  
  filter(percent_change > 0) %>% 
  ggplot(aes(days_since_first_paper, percent_change_lag, group = group)) +
  geom_line() +
  facet_wrap(vars(dataset)) +
  scale_y_log10()
```

## CIFAR-100

```{r}
sota %>% 
  filter(dataset == "CIFAR-100") %>% 
  filter(metric_name == "Percentage correct") %>% 
  ggplot(aes(paper_date, metric_result)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
sota %>% 
  # filter(dataset == "ImageNet") %>% 
  #filter(task == "Image Classification") %>% 
  filter(dataset %in% c("CIFAR-100")) %>% 
  filter(metric_name == "Percentage correct") %>% 
  drop_na(percent_change_lag) %>% 
  ggplot(aes(paper_date, percent_change_lag, group = group)) +
  geom_point() +
  geom_line() 
```

## Ideas

* Sum?
* Percent change of current from first
  * To collapse, maybe weight by number of observations?
* Median of each line, look at how individual values deviate 


