---
title: Papers with Code - SOTA
author: Sara Altman 
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(lubridate)
# devtools::install_github("njtierney/brolgar")
library(brolgar)

# Parameters
MIN_OBSERVATIONS <- 5
file_sota <- here::here("data/sota/sota.rds")
file_group_counts <- here::here("data/sota/groups.rds")
file_fixes <- here::here("data/sota/fixes.yml")
QUANTILE_CUTOFF <- 0.95
#===============================================================================

fixes <-
  yaml::read_yaml(file_fixes) %>%
  enframe(name = "result_id", value = "metric_result") %>% 
  unnest_wider(col = metric_result) 

sota_all <-
  file_sota %>% 
  read_rds() %>% 
  drop_na(paper_date, metric_result) %>% 
  # rows_update(fixes, by = "result_id") %>% 
  group_by(group) %>% 
  mutate(
    n_results = n(),
    metric_result = if_else(minimize, metric_result * -1, metric_result),
    percent_change = 
      (metric_result - lag(metric_result, order_by = paper_date)) / 
      abs(lag(metric_result, order_by = paper_date)),
    log_percent_change = log(percent_change),
    days_since_first_paper = (min(paper_date) %--% paper_date) / days(1)
  ) %>% 
  ungroup() 

sota <-
  sota_all %>% 
  filter(percent_change < Inf) %>% 
  group_by(year(paper_date)) %>% 
  filter(percent_change < quantile(percent_change, QUANTILE_CUTOFF)) %>% 
  ungroup() 
```

```{r}
sota_all %>% 
  slice_min(percent_change, n = 5)
```


```{r}
sota %>%  
  ggplot(aes(percent_change)) +
  geom_histogram(binwidth = .1) +
  scale_x_continuous(labels = scales::label_percent())

sota %>% 
  group_by(year(paper_date)) %>% 
  summarize(
    percent_outliers
  )
  filter(percent_change >= quantile(.$percent_change, .9)) %>% 
  ggplot(aes(year(paper_date))) +
  geom_bar()

sota %>% 
  filter(!str_detect(str_to_lower(metric_name), "params")) %>% 
  filter(percent_change > 2) %>% 
  select(group, paper_title, metric_name, percent_change) %>% 
  arrange(desc(percent_change))
```

```{r}
sota %>% 
  mutate(year = year(paper_date)) %>% 
  ggplot(aes(year, percent_change, group = year)) +
  geom_boxplot() +
  scale_y_log10()
```

```{r}
sota_all %>% 
  filter(group == "Atari Games_Atari 2600 Phoenix_Score")
```

## Number of SOTA results, by year

```{r}
sota %>%  
  filter(
    days_since_first_paper > 0, 
    year(paper_date) < 2020
  ) %>% 
  mutate(
    significant = 
      case_when(
        percent_change >= 0.5 ~ "Results with at least 50% increase",
        percent_change >= 0.1 ~ "Results with at least 10% increase",
        TRUE                  ~ "All results"
      )
  ) %>% 
  count(significant, year = year(paper_date)) %>%
  ggplot(aes(year, n, color = significant)) +
  geom_point() +
  geom_line() + 
  scale_x_continuous(breaks = scales::breaks_width(1)) +
  scale_y_continuous(breaks = scales::breaks_width(100)) +
  labs(
    x = "Year",
    y = "Number of results",
    color = NULL,
    title = "Number of SOTA results by year"
  )
```

```{r message=FALSE}
v <-
  sota %>% 
  group_by(year = year(paper_date)) %>%
  summarize(
    `all` = n(),
    `10% increase` = sum(percent_change > 0.1, na.rm = TRUE),
    `50% increase` = sum(percent_change > 0.5, na.rm = TRUE),
    `100% increase` = sum(percent_change > 1, na.rm = TRUE),
    across(
      contains("%"), 
      list(percent = ~ (. / n()) * 100), 
      .names = "{col} ({fn})"
    )
  ) 

v %>% 
  knitr::kable(digits = 2)
```

## Percent change over time

```{r warning=FALSE}
sota %>% 
  drop_na(percent_change) %>%
  ggplot(aes(paper_date, percent_change)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm", formula = "y~x") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  scale_y_log10(
    labels = scales::label_percent(big.mark = ",")
  ) +
  labs(
    x = "Paper publication date",
    y = "Percent change from previous SOTA result\n(log scale)",
    title = "Percent change of SOTA results over time"
  )
```

## Average percent change per year

```{r results='asis'}
v <-
  sota %>% 
  drop_na(percent_change) %>% 
  mutate(year = year(paper_date)) %>% 
  group_by(year) %>% 
  summarize(
    med_percent_change = median(percent_change)
  ) %>%
  arrange(desc(year))
```

### Table

```{r}
v %>% 
  mutate(med_percent_change = round(med_percent_change * 100, 1)) %>% 
  rename(
    Year = year,
    "Median percent change" = med_percent_change
  ) 
```

### Plot

```{r}
v %>% 
  ggplot(aes(year, med_percent_change)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = scales::breaks_width(1)) +
  scale_y_continuous(
    labels = scales::label_percent(accuracy = 1),
    breaks = scales::breaks_width(0.02),
    limits = c(0, .16)
  ) +
  labs(
    x = "Year",
    y = "Median percent change",
    title = "Median percent change in SOTA results by year"
  )
```

## Total percent change by year

```{r}
v <-
  sota %>% 
  drop_na(percent_change) %>% 
  mutate(year = year(paper_date)) %>% 
  filter(year < 2020) %>% 
  group_by(year) %>% 
  summarize(total_percent_change = sum(percent_change)) %>%
  arrange(desc(year))
```

### Table

```{r}
v %>% 
  mutate(total_percent_change = round(total_percent_change * 100, 1)) %>% 
  rename(
    Year = year,
    "Total percent change" = total_percent_change
  ) 
```

### Plot

```{r}
v %>% 
  ggplot(aes(year, total_percent_change)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = scales::breaks_width(1)) +
  scale_y_continuous(labels = scales::label_percent(big.mark = ",")) +
  labs(
    x = "Year",
    y = "Total percent change",
    title = "Total percent change by year"
  )
```

## Models

```{r}
sota_ts <-
  sota %>% 
  drop_na(percent_change) %>%  
  mutate(percent_change = percent_change * 100) %>% 
  as_tsibble(
    key = group,
    index = paper_date,
    regular = FALSE
  ) %>% 
  add_n_obs() %>% 
  filter(n_obs > 1)
```

```{r}
slopes <-
  sota_ts %>% 
  key_slope(percent_change ~ paper_date)

slopes %>% 
  filter(
    .slope_paper_date < quantile(.slope_paper_date, .975),
    .slope_paper_date > quantile(.slope_paper_date, .025)
  ) %>% 
  ggplot(aes(.slope_paper_date)) +
  geom_histogram(binwidth = 0.02) +
  geom_vline(
    aes(xintercept = median(.slope_paper_date)),
    color = "blue"
  ) +
  labs(
    title = "Distribution of slopes",
    subtitle = "Top and bottom 2.5% excluded",
    x = "Slope",
    y = "Count"
  )
```

```{r}
enframe(
  quantile(slopes$.slope_paper_date),
  name = "quantile"
) %>% 
  mutate(value = round(value, 3))
```

```{r}
slopes %>% 
  count(positive = .slope_paper_date > 0) %>% 
  mutate(pct = n / sum(n)) 
```

## Investigation

```{r}
sota %>% 
  mutate(year = year(paper_date)) %>% 
  group_by(year) %>% 
  slice_max(percent_change) %>% 
  ungroup() %>% 
  select(year, percent_change)
```

```{r}
sota %>% 
  filter(year(paper_date) == 2018) %>% 
  slice_max(n = 1, order_by = percent_change)
``` 

```{r}
sota_all %>% 
  filter(str_detect(group, "Video Object Segmentation_YouTube-VOS_Speed"))
```

Check: is the number of metrics measured changing over time

Link Prediction_FB15k_MR
fix link prediction issue ff
```{r}
sota_all %>% 
  filter(group == "Link Prediction_FB15k_MR")
```

2019

```{r}
sota_all %>% 
  filter(str_detect(group, "Density Estimation_MNIST"))
```

```{r}
sota_all %>% 
  ggplot(aes(metric_result)) +
  geom_histogram() +
  scale_x_log10()

quantile(sota_all$metric_result, na.rm = TRUE)
```

