---
title: "Notes"
author: "Sara Altman"
date: "2020-01-30"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intro

## Are ideas getting harder to find?

* Research effort is rising, while research productivity is declining sharply
* Moore's law---number of researchers required to achieve the doubling every two years is  18x larger than the number required in the 1970s
* Ideas and the exponential growth they imply are getting harder to find

## Introduction

* economic growth = research productivity x number of researchers
* selected cases where they were able to attain data on the "idea output" and the "research input"

## Conceptual framework

* research productivity = # of new ideas /  # of researchers
* Ideas as proportional improvements in productivity
* Ideas as exponential growth

## AI index

seems like they are just searching for the term in the text of the paper, e.g., "ImageNet". This paper only mentions ImageNet in passing: https://arxiv.org/pdf/1705.01217.pdf

# Citations

## Google Scholar

Limits; search by title

## Open citations

Need to search by DOI

## Crossref

Can get citations by title
If I do title-by-title, will take 53 hours
Doesn't get all the papers. Maybe around 50%

## Elsevier

Citation counts might be off?

## Microsoft



