---
title: Researchers
author: 
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(lubridate)

# Parameters
MAX_DATE <- "2019-12-31"
DATE_BREAKS <- "5 years"
RESEARCHER_BREAKS <- 1 * 10^(seq(0, 5))
RESEARCHER_LIMITS <- c(1, 1e5)
FACTOR_INCREASE_YEARS_1 <- c(1999, 2019)
FACTOR_INCREASE_YEARS_2 <- c(2009, 2019)
  # File with authors data
file_authors <-       
  here::here("data/microsoft/ms_authors.rds")
  # File with authors by subfield
file_authors_subfields <- 
  here::here("data/microsoft/ms_authors_subfields.rds")
  # File with subfield code-name mappings
file_subfields <- here::here("data/arxiv/subfields.yml")
  # File with new authors + citation thresholds
file_authors_citations <- here::here("data/microsoft/ms_authors_citations.rds")

citation_levels <-
  c(
    "All authors",
    "No citations",
    "At least 1 citation",
    "At least 5 citations",
    "At least 10 citations",
    "At least 100 citations",
    "At least 1000 citations"
  )
#===============================================================================

authors <-
  file_authors %>% 
  read_rds() %>% 
  filter(date < MAX_DATE)

subfields <-
  file_subfields %>% 
  yaml::read_yaml() %>% 
  map_dfr(~ tibble(field = .$field, code = .$code), .id = "name")

authors_subfields <-
  file_authors_subfields %>% 
  read_rds() %>% 
  left_join(subfields, by = c("subfield" = "code")) %>% 
  filter(date < MAX_DATE) %>% 
  relocate(field, name, subfield, .after = date) %>% 
  rename(subfield_name = name, subfield_code = subfield)

authors_citations <-
  file_authors_citations %>% 
  read_rds() %>% 
  filter(date < MAX_DATE)
```

## New researchers

### Total researchers over time

```{r}
authors %>% 
  ggplot(aes(date, total_authors)) +
  geom_line() +
  coord_cartesian(ylim = RESEARCHER_LIMITS) +
  scale_x_date(date_breaks = DATE_BREAKS, date_labels = "%Y") +
  scale_y_log10(
    breaks = RESEARCHER_BREAKS,
    labels = scales::label_comma(accuracy = 1)
  ) +
  labs(
    x = "Date",
    y = "Total researchers",
    title = "Total researchers over time",
    caption = "Source: arXiv and Microsoft"
  )
```

### New researchers (table)

```{r}
authors_by_year <-
  authors %>% 
  group_by(year = year(date)) %>% 
  summarize(new_researchers = sum(new_authors))

authors_by_year %>% 
  mutate(
    total_researchers = cumsum(new_researchers),
    `% new researchers` =
      (lag(new_researchers) / new_researchers) * 100,
    `% growth of total researchers` = 
      ((total_researchers - lag(total_researchers)) / 
         lag(total_researchers)) * 100
  ) %>% 
  rename(
    Year = year,
    `New researchers` = new_researchers,
    `Total researchers` = total_researchers
  ) %>% 
  knitr::kable(
    digits = 2
  )
```

### Factor increase (table)

```{r}
factor_increase <- function(var, var_year, years) {
  var[var_year == years[[2]]] / var[var_year == years[[1]]]
}

authors_by_year %>% 
  mutate(total_researchers = cumsum(new_researchers)) %>% 
  summarize(
    across(
      -year, 
      list(
        `1999-2019` = ~ .[year == 2019] / .[year == 1999],
        `2009-2019` = ~ .[year == 2019] / .[year == 2009]
      )
    )
  ) %>% 
  pivot_longer(
    cols = everything(), 
    names_to = c("variable", "period"),
    names_pattern = "(.*)_(\\d+-\\d+)"
  ) %>% 
  pivot_wider(names_from = variable, values_from = value) %>% 
  rename(
    Period = period,
    `New researchers factor increase` = new_researchers,
    `Total researchers factor increase` = total_researchers
  ) %>% 
  knitr::kable(digits = 3)
```

### Total authors by subfield per year 

```{r}
authors_subfields %>% 
  mutate(
    subfield_name = 
      str_wrap(subfield_name, width = 20) %>% fct_reorder2(date, total_authors)
  ) %>% 
  ggplot(aes(date, total_authors, color = subfield_name)) + 
  geom_line() +
  coord_cartesian(ylim = RESEARCHER_LIMITS) +
  scale_x_date(date_breaks = DATE_BREAKS, date_labels = "%Y") +
  scale_y_log10(
    breaks = RESEARCHER_BREAKS,
    labels = scales::label_comma(accuracy = 1)
  ) +
  theme(
    legend.text = element_text(size = 5)
  ) +
  labs(
    title = "Total researchers over time, by subfield",
    x = "Date",
    y = "Total researchers",
    color = NULL,
    caption = "Source: arXiv and Microsoft"
  ) 
```

### Total authors by subfield per year (table)

```{r}
authors_subfields %>%
  mutate(
    subfield =
      str_glue("{subfield_name} ({subfield_code})") %>% as.character()
  ) %>%
  group_by(year = year(date), subfield) %>%
  summarize(new_authors = sum(new_authors)) %>%
  ungroup() %>%
  mutate(total_authors = cumsum(new_authors)) %>%
  select(-new_authors) %>%
  pivot_wider(
    names_from = subfield,
    values_from = total_authors,
    values_fill = list(total_authors = 0)
  ) %>% 
  knitr::kable()
```

## New researchers -- citation thresholds

```{r}
v <-
  authors_citations %>% 
  bind_rows(
    authors %>% mutate(citation_group = "All authors")
  ) %>% 
  filter(year(date) >= 1990) %>% 
  mutate(
    citation_group = factor(citation_group, levels = citation_levels)
  )

v %>% 
  ggplot(aes(date, total_authors, color = citation_group)) +
  geom_line() +
  coord_cartesian(ylim = RESEARCHER_LIMITS) + 
  scale_x_date(
    breaks = 
      seq(ymd("1990-01-01"), ymd("2020-01-01"), "5 years"), 
    date_labels = "%Y"
  ) +
  scale_y_log10(
    breaks = RESEARCHER_BREAKS,
    labels = scales::label_comma(accuracy = 1)
  ) +
  theme(
    legend.text = element_text(size = 6)
  ) +
  labs(
    x = "Date",
    y = "Total researchers",
    color = NULL,
    title = "Total researchers over time",
    subtitle = "By maximum number of citations on a paper",
    caption = "Source: arXiv and Microsoft"
  )
```

```{r}
v <-
  v %>% 
  filter(citation_group == "At least 1000 citations")

v %>% 
  filter(year(date) > 2010) %>% 
  ggplot(aes(date, total_authors)) +
  geom_line() +
  coord_cartesian(ylim = c(1, 300)) +
  scale_x_date(
    breaks = 
      seq(ymd("1990-01-01"), ymd("2020-01-01"), "5 years"), 
    date_labels = "%Y"
  ) +
  scale_y_log10(breaks = scales::breaks_log(n = 8)) +
  theme(
    legend.text = element_text(size = 6)
  ) +
  labs(
    x = "Date",
    y = "Total researchers",
    color = NULL,
    title = "Researchers with at least 1000 citations over time",
    caption = "Source: arXiv and Microsoft"
  )
```




